### ISSUE TITLE
Milestone 1 Comment

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/dsci525-gr9#11]
Comments:
- Did not include Teamwork contract in canvas submission (-10)
- Error in markdown table in question 5.2 

Final Score: 90/100

**Comment by Glenn032787** [comment]
Feel free to send me your teamwork contract on slack or in this issue to receive the mark!

**Comment by stepanz25** [comment]
Hi @Glenn032787! Here is our Team Work contract: https://docs.google.com/document/d/12_ieMhBh4RPM0LjiJZU35JLZx0srPnyXWPlSboVQJ2Q/edit#

**Comment by Glenn032787** [comment]
Thanks! I have give you the marks back.
